import Head from "next/head"
export default function PageHead({pageName}) {
	return (
	<Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
	)
}